#!/usr/bin/env python3
"""
build_index.py — Rebuild documentation indexes for MediaTrackerPlus.

Implements the reindexing rules from REINDEX.md:
  R1  Master index  (docs/INDEX.md)
  R2  In-file tables of contents
  R4  API index from server/openapi.json

Usage:
    python .claude/skills/documenter/scripts/build_index.py
    python .claude/skills/documenter/scripts/build_index.py --index-only
    python .claude/skills/documenter/scripts/build_index.py --api
    python .claude/skills/documenter/scripts/build_index.py --toc README.md
    python .claude/skills/documenter/scripts/build_index.py --dry-run
"""

from __future__ import annotations

import argparse
import json
import logging
import re
import sys
from collections import defaultdict
from datetime import date
from pathlib import Path
from typing import Optional

logging.basicConfig(
    level=logging.INFO,
    format="%(levelname)s %(message)s",
    stream=sys.stderr,
)
logger = logging.getLogger(__name__)

CATALOG_FILENAME = "docs-catalog.json"
INDEX_PATH_REL = "docs/INDEX.md"
API_README_REL = "docs/api/README.md"
OPENAPI_REL = "server/openapi.json"
TOC_MIN_SECTIONS = 5  # Minimum H2 sections to trigger TOC insertion


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def find_repo_root(start: Path) -> Path:
    for candidate in [start.resolve(), *start.resolve().parents]:
        if (candidate / "package.json").exists() or (candidate / ".git").exists():
            return candidate
    raise FileNotFoundError("Cannot determine repository root.")


def load_catalog(repo_root: Path) -> dict:
    catalog_path = repo_root / CATALOG_FILENAME
    if not catalog_path.exists():
        raise FileNotFoundError(
            f"{CATALOG_FILENAME} not found. Run scan_docs.py first."
        )
    return json.loads(catalog_path.read_text(encoding="utf-8"))


def extract_title(content: str) -> Optional[str]:
    """Return the first H1 text from Markdown content."""
    for line in content.splitlines():
        stripped = line.strip()
        if re.match(r"^# [^#]", stripped):
            return stripped[2:].strip()
    return None


def extract_description(content: str) -> str:
    """
    Return the first non-blank, non-heading paragraph after the H1.
    Falls back to '(no description)'.
    """
    lines = content.splitlines()
    past_h1 = False
    for line in lines:
        stripped = line.strip()
        if not past_h1:
            if re.match(r"^# [^#]", stripped):
                past_h1 = True
            continue
        if stripped and not stripped.startswith("#") and not stripped.startswith("---"):
            # Strip leading badge markdown
            clean = re.sub(r"!\[.*?\]\(.*?\)", "", stripped).strip()
            if clean:
                return clean[:120] + ("..." if len(clean) > 120 else "")
    return "(no description)"


def heading_to_anchor(text: str) -> str:
    """
    Convert a heading text to a GitHub Flavored Markdown anchor slug.
    """
    text = text.lower()
    text = re.sub(r"[^\w\s-]", "", text)
    text = re.sub(r"\s+", "-", text)
    text = re.sub(r"-+", "-", text)
    return text.strip("-")


def extract_h2_sections(content: str) -> list[str]:
    """Return all H2 heading texts from content (not inside code fences)."""
    sections: list[str] = []
    in_fence = False
    for line in content.splitlines():
        stripped = line.strip()
        if stripped.startswith("```") or stripped.startswith("~~~"):
            in_fence = not in_fence
        if in_fence:
            continue
        m = re.match(r"^## ([^#].*)", stripped)
        if m:
            sections.append(m.group(1).strip())
    return sections


# ---------------------------------------------------------------------------
# R1 — Master index
# ---------------------------------------------------------------------------


def build_master_index(catalog: dict, repo_root: Path) -> str:
    """Generate the content of docs/INDEX.md from the catalog."""
    today = date.today().isoformat()

    # Group files by top-level directory relative to repo root
    groups: dict[str, list[dict]] = defaultdict(list)
    for file_info in catalog["files"]:
        if file_info.get("is_generated"):
            continue
        rel = file_info["rel_path"]
        parts = Path(rel).parts
        group = parts[0] if len(parts) > 1 else "root"
        groups[group].append(file_info)

    lines: list[str] = [
        "# Documentation Index",
        "",
        f"> Last updated: {today} — generated by `build_index.py`",
        "",
        "## Quick Links",
        "",
        "- [Getting Started](../README.md)",
        "- [API Reference](api/README.md)",
        "- [Configuration](configuration/README.md)",
        "- [Deployment](deployment/README.md)",
        "- [Integrations](integrations/README.md)",
        "- [Development](development/README.md)",
        "",
        "## All Files",
        "",
    ]

    for group in sorted(groups.keys()):
        section_title = "Root" if group == "root" else group.replace("-", " ").title()
        lines.append(f"### {section_title}")
        lines.append("")
        lines.append("| File | Description |")
        lines.append("|------|-------------|")

        for file_info in sorted(groups[group], key=lambda f: f["rel_path"]):
            rel = file_info["rel_path"]
            title = file_info.get("title") or Path(rel).stem.replace("-", " ").title()

            # Build a relative link from docs/INDEX.md to the file
            try:
                link_target = Path("..") / rel
            except Exception:
                link_target = Path(rel)

            abs_path = file_info.get("abs_path", "")
            if abs_path and Path(abs_path).exists():
                desc = extract_description(Path(abs_path).read_text(encoding="utf-8", errors="replace"))
            else:
                desc = "(no description)"

            lines.append(f"| [{title}]({link_target}) | {desc} |")

        lines.append("")

    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# R2 — In-file table of contents
# ---------------------------------------------------------------------------


def build_toc(sections: list[str]) -> list[str]:
    """Build a Markdown TOC list from a list of H2 section titles."""
    toc_lines: list[str] = [
        "## Contents",
        "",
    ]
    for section in sections:
        anchor = heading_to_anchor(section)
        toc_lines.append(f"- [{section}](#{anchor})")
    toc_lines.append("")
    return toc_lines


def inject_toc(content: str, changes: list[str]) -> str:
    """
    Insert or replace a ## Contents section after the H1 title.
    Only applied when the file has >= TOC_MIN_SECTIONS H2 sections.
    """
    sections = extract_h2_sections(content)
    # Exclude any existing "Contents" section from the count
    sections_excluding_toc = [s for s in sections if s.lower() not in ("contents", "table of contents")]

    if len(sections_excluding_toc) < TOC_MIN_SECTIONS:
        return content

    toc_lines = build_toc(sections_excluding_toc)
    toc_block = "\n".join(toc_lines)

    # Remove existing ## Contents block if present
    content = re.sub(
        r"## (?:Contents|Table of Contents)\n[\s\S]*?(?=\n## |\Z)",
        "",
        content,
    )

    # Insert after H1 (and optional metadata/badge lines)
    lines = content.split("\n")
    insert_at = 0
    past_h1 = False
    for i, line in enumerate(lines):
        if re.match(r"^# [^#]", line.strip()):
            past_h1 = True
            insert_at = i + 1
            continue
        if past_h1:
            if line.strip() == "" or line.strip().startswith("[!["):
                insert_at = i + 1
            else:
                break

    new_lines = lines[:insert_at] + ["", *toc_block.split("\n"), "---", ""] + lines[insert_at:]
    changes.append(f"Injected ## Contents TOC ({len(sections_excluding_toc)} sections)")
    return "\n".join(new_lines)


# ---------------------------------------------------------------------------
# R4 — API index from openapi.json
# ---------------------------------------------------------------------------


def build_api_index(openapi_path: Path) -> str:
    """Generate docs/api/README.md from server/openapi.json."""
    if not openapi_path.exists():
        raise FileNotFoundError(f"OpenAPI spec not found: {openapi_path}")

    spec = json.loads(openapi_path.read_text(encoding="utf-8"))
    today = date.today().isoformat()
    info = spec.get("info", {})
    title = info.get("title", "API Reference")
    version = info.get("version", "unknown")
    description = info.get("description", "")

    # Group paths by tag
    tagged: dict[str, list[dict]] = defaultdict(list)
    paths = spec.get("paths", {})

    for path, methods in paths.items():
        for method, operation in methods.items():
            if method.upper() not in ("GET", "POST", "PUT", "PATCH", "DELETE", "HEAD", "OPTIONS"):
                continue
            tags = operation.get("tags", ["Untagged"])
            for tag in tags:
                tagged[tag].append({
                    "method": method.upper(),
                    "path": path,
                    "summary": operation.get("summary", ""),
                    "deprecated": operation.get("deprecated", False),
                })

    lines: list[str] = [
        f"# {title}",
        "",
        f"> Version: `{version}` — Source: `server/openapi.json`  ",
        f"> Last regenerated: {today} — run `build_index.py --api` to update",
        "",
    ]

    if description:
        lines += [description, ""]

    lines += [
        "Full interactive documentation: https://dnlwttnbrg.github.io/MediaTrackerPlus/",
        "",
        "## Endpoints",
        "",
    ]

    for tag in sorted(tagged.keys()):
        lines.append(f"### {tag}")
        lines.append("")
        lines.append("| Method | Path | Summary |")
        lines.append("|--------|------|---------|")
        for endpoint in sorted(tagged[tag], key=lambda e: (e["path"], e["method"])):
            deprecated = " *(deprecated)*" if endpoint["deprecated"] else ""
            lines.append(
                f"| `{endpoint['method']}` | `{endpoint['path']}` "
                f"| {endpoint['summary']}{deprecated} |"
            )
        lines.append("")

    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Build documentation indexes for MediaTrackerPlus.",
    )
    parser.add_argument(
        "--index-only",
        action="store_true",
        help="Only rebuild docs/INDEX.md",
    )
    parser.add_argument(
        "--api",
        action="store_true",
        help="Only rebuild docs/api/README.md from openapi.json",
    )
    parser.add_argument(
        "--toc",
        type=Path,
        default=None,
        metavar="FILE",
        help="Inject/update TOC in a specific file",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print what would be written without modifying files",
    )
    return parser.parse_args(argv)


def write_or_print(path: Path, content: str, dry_run: bool) -> None:
    if dry_run:
        print(f"\n--- Would write: {path} ---\n")
        print(content[:2000])
        if len(content) > 2000:
            print(f"... ({len(content) - 2000} more chars)")
    else:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        logger.info("Written: %s", path)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv or sys.argv[1:])

    try:
        repo_root = find_repo_root(Path(__file__))
    except FileNotFoundError as exc:
        logger.error("%s", exc, exc_info=True)
        return 1

    # --toc mode: only rebuild TOC for one file
    if args.toc:
        toc_path = args.toc.resolve()
        if not toc_path.exists():
            logger.error("File not found: %s", toc_path)
            return 1
        content = toc_path.read_text(encoding="utf-8")
        toc_changes: list[str] = []
        updated = inject_toc(content, toc_changes)
        if toc_changes:
            write_or_print(toc_path, updated, args.dry_run)
            for change in toc_changes:
                logger.info("  %s: %s", toc_path.name, change)
        else:
            logger.info("No TOC changes needed for %s", toc_path)
        return 0

    # --api mode: only rebuild API index
    if args.api:
        openapi_path = repo_root / OPENAPI_REL
        try:
            api_content = build_api_index(openapi_path)
        except (FileNotFoundError, json.JSONDecodeError, KeyError) as exc:
            logger.error("Failed to build API index: %s", exc, exc_info=True)
            return 1
        write_or_print(repo_root / API_README_REL, api_content, args.dry_run)
        return 0

    # Full reindex (default)
    try:
        catalog = load_catalog(repo_root)
    except FileNotFoundError as exc:
        logger.error("%s", exc, exc_info=True)
        return 1

    exit_code = 0

    if not args.api:  # Build master index unless --api only
        index_content = build_master_index(catalog, repo_root)
        write_or_print(repo_root / INDEX_PATH_REL, index_content, args.dry_run)

    if not args.index_only:
        # Rebuild API index
        openapi_path = repo_root / OPENAPI_REL
        if openapi_path.exists():
            try:
                api_content = build_api_index(openapi_path)
                write_or_print(repo_root / API_README_REL, api_content, args.dry_run)
            except (json.JSONDecodeError, KeyError) as exc:
                logger.error("Failed to build API index: %s", exc, exc_info=True)
                exit_code = 1
        else:
            logger.warning("openapi.json not found at %s; skipping API index.", openapi_path)

        # Inject/update TOC in files with enough sections
        for file_info in catalog.get("files", []):
            if file_info.get("is_generated"):
                continue
            if len(file_info.get("h2_sections", [])) < TOC_MIN_SECTIONS:
                continue
            file_path = Path(file_info["abs_path"])
            if not file_path.exists():
                continue
            content = file_path.read_text(encoding="utf-8", errors="replace")
            toc_changes: list[str] = []
            updated = inject_toc(content, toc_changes)
            if toc_changes:
                write_or_print(file_path, updated, args.dry_run)
                for change in toc_changes:
                    logger.info("  %s: %s", file_info["rel_path"], change)

    return exit_code


if __name__ == "__main__":
    sys.exit(main())
